name: collection-blog
on:
  push:
    branches: [main]
  schedule:
    # 定时任务，在每天的5点推送信息到邮箱
    - cron: '0 21 * * *'

env:
    cache-name: note
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Version
        run: node -v
  
      - name: Cache nodemodules
        uses: actions/cache@v3
        env:
            cache-name: cache-node-modules
        with:
            # 需要缓存的文件的路径
            path: ./node_modules 
            # 对缓存的文件指定的唯一标识
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }} 
            # 用于没有再找目标key的缓存的backup选项
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-
                ${{ runner.os }}-build-
                ${{ runner.os }}-

      - name: Install
        run: npm install # 安装依赖

      - name: Build
        env:
          QQ_PASS: ${{secrets.QQ_PASS}}
        run: npm run build
      
      - name: Copy
        run: cp README.md dist && cd dist && ls && cd ..

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4 # 使用部署到 GitHub pages 的 action
        with:
          # 发布到指定分支
          BRANCH: gh-pages
          # 构建成果所在目录,默认位置都是在根目录
          FOLDER: ./dist
